### ISSUE TITLE
[Can't compile] Module file was created by an older version of  the compiler

### ISSUE THREAD

**Issue by lfarah** [spanage/AccessibilityAnnouncer#5]
<img width="682" alt="screen shot 2016-08-16 at 10 52 57 pm" src="https://cloud.githubusercontent.com/assets/6511079/17725942/404b7a0e-6404-11e6-978f-a0e383cfd6d8.png">

**Comment by spanage** [comment]
Updated as of: 20ab34cbbce57adbded36d7cd80c8ad70fe6e0db - thank you!
