### ISSUE TITLE
Cannot compile for Swift 3

### ISSUE THREAD

**Issue by maysamsh** [spanage/AccessibilityAnnouncer#6]
After upgrade for Swift 3.0 I cannot compile it:
`/AccessibilityAnnouncer.swift:22:35: Use of undeclared type 'SignalProducer'`
`/AccessibilityAnnouncer.swift:25:29: Use of undeclared type 'Signal'`
`/AccessibilityAnnouncer.swift:27:33: Use of undeclared type 'Disposable'`
`/AccessibilityAnnouncer.swift:58:91: Use of unresolved identifier 'QueueScheduler'`

**Comment by spanage** [comment]
Commit 20ab34cbbce57adbded36d7cd80c8ad70fe6e0db updates to Swift 4.0
